### ISSUE TITLE
Implement sign in with google API.

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderApp#7] opened 2023-05-20 14:27 UTC
Sign in with google API is already implemented in sign up activity but under this issue you have to implement it in sign in activity.
What is need of this ?
when some one try to use sign in with google feature in sign up activity use have to select username but in sign in activity if user already registered in database then it should sign in app other wise fails to sign in.

**Comment by harsh2907** [comment] 2023-05-20 14:39
Please assign this issue to me, i will resolve this

**Comment by shags8** [comment] 2023-05-20 16:05
Assign me this please

**Comment by Yash-Parsana** [comment] 2023-05-20 18:45
issue #

**Comment by Yash-Parsana** [comment] 2023-05-20 19:03
@harsh2907 
This issue is assiged to you under gssoC'23

**Comment by harsh2907** [comment] 2023-05-21 05:40
While working on google sign up its not working i mean when i click on sign in with google the account pop up shows but when i select the account its not working on further debugging i got to know its giving RESULT_CANCELLED instead of RESULT_SUCCESS so if you know the cause that would be a great help

**Comment by Yash-Parsana** [comment] 2023-05-23 17:36
I don't have more idea about this problem but as per my knowledge when we try to use this sign in with google api in more than one activity it generally cause some issue it might be this one.

**Comment by Ashok-Kumar-dharanikota** [comment] 2023-05-24 05:30
Hi @Yash-Parsana , I faced a similar issue, while I was working on some other project. I would like to work on this. If you find it okay. Please assign it to me. Thank you

**Comment by Yash-Parsana** [comment] 2023-05-25 16:14
@harsh2907 
Can you solve this issue or i should assign to other ?

**Comment by harsh2907** [comment] 2023-05-27 16:48
Assign it to someone else

**Comment by Ashok-Kumar-dharanikota** [comment] 2023-05-29 12:53
Hey @Yash-Parsana , i would like to work on this issue. If you find it okay.

**Comment by AKsHaT123456A** [comment] 2023-06-01 05:09
Hi @Yash-Parsana ,can you assign me this issue?

**Comment by priyanshu942** [comment] 2023-06-02 11:32
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by Yash-Parsana** [comment] 2023-06-05 13:44
Hello @Ashok-Kumar-dharanikota this issue is assigned to you under gssoc23

**Comment by Ashok-Kumar-dharanikota** [comment] 2023-06-09 16:41
Hi @Yash-Parsana,

 I am currently working on implementing the Google Sign-In feature and have encountered some issues along the way. However, I would appreciate your assistance in clarifying a particular matter.

In the event that a user chooses to log in using the traditional method by manually entering their email and password credentials, I would like to inquire whether these credentials are saved in shared preferences. Furthermore, I would like to confirm whether we can utilize these stored credentials to retrieve the user's data from Firebase and subsequently update various UI components such as the username.

I have examined the existing codebase but would greatly appreciate your confirmation on this matter. Your insights would be highly valuable in ensuring the accuracy and effectiveness of the implementation.

**Comment by oshinsaraf** [comment] 2023-06-11 11:10
Can you assign me this under GSSOC'23?

**Comment by Ashok-Kumar-dharanikota** [comment] 2023-06-16 14:33
Hi @Yash-Parsana 

Thank you for giving me more time then usual. But I regret to share that  I didn't come up with a solution. I didn't get much time to work on this issue. Please assign the issue to someone. I also work parallelly if I figure it out. I will let you know.

**Closed as completed** 2023-06-20 10:58 UTC
Labels: gssoc23, level3
